### ISSUE TITLE
Save not working

### ISSUE THREAD

**Issue by AndersenJ** [pelmers/moz-text-rewriter#1]
When I try to save my substitutions, it doesn't work. It appears to work, but the substitutions don't apply and when I go to check them again they're gone. This plugin has worked for me in the past though, so I'm wondering if perhaps a firefox update caused this issue.

**Comment by pelmers** [comment]
Hi, thanks for the issue report. It looks like the plan to remove legacy add-ons is in motion and has broken this extension.

The fix will be to rewrite it as a WebExtension. I expect I will do that by next week.

**Comment by pelmers** [comment]
should be fixed in 0a5f83e039142d42b18f2ab9b9a026cbdc15b2a1
