### ISSUE TITLE
Smart Case not working for Suffixes

### ISSUE THREAD

**Issue by rwiesbach** [pelmers/moz-text-rewriter#11]
If I replace Teacher -> Student with Smart Case enabled, I would expect that Mathteacher becomes Mathstudent. In fact, it becomes MathStudent .

**Comment by pelmers** [comment]
Hi @rwiesbach, the right thing to do here is probably to adjust the starting regex to exclude prefixes. If you only want to match when the pattern is not a suffix, you can start it with `\b`. That will only match the input on a word boundary (e.g. a space); you can try it out on https://regex101.com/.

**Comment by pelmers** [comment]
I did try to repro this issue and don't see it happening here.
I added this rule `{"from":"Teacher","to":"Student","ic":false,"mw":false,"sc":true}`, and I see:
`If I replace Student -> Student with Smart Case enabled, I would expect that Mathstudent becomes Mathstudent. In fact, it becomes MathStudent .`
