### ISSUE TITLE
Very strange behavior with escaping slashes.

### ISSUE THREAD

**Issue by Predelnik** [pelmers/moz-text-rewriter#12]
If I input "\(" in phrase textbox and press save it results in "\\(" which is incorrect since I want escaped parentheses and can't input it by any other method.
Trying to input something akin to this in bottom box also lead to some strange results and import button seems to not work after that.

I'm using firefox version if that's important.

**Comment by pelmers** [comment]
Are you matching on `(` or `"("`? I was able to match on both without a problem by escaping each special character in the text box.

For example, my `from` field was `\"\(\"` to match the second case.

**Comment by Predelnik** [comment]
Examples;
Input:
```
(
```
Output:
```
[{"from":"(","to":"misspell","ic":false,"mw":false,"sc":false}]
```
No escaping for `(`
Input:
```
\(
```
Output:
```
[{"from":"\\(","to":"misspell","ic":false,"mw":false,"sc":false}]
```
Escaping only for `\`
Input:
```
"("
```
Input:
```
[{"from":"\"(\"","to":"misspell","ic":false,"mw":false,"sc":false}]
```
Escaping only for `"`
So `(` is not escaped for me somehow as it is in your example, very strange

**Comment by Predelnik** [comment]
~~I see in the source code that you use `JSON.stringify` to convert which probably escapes for subsequent use within string but since the resulting text is regexp, it is actually unhelpful because I can't input `\(` at the top input and have to use double slash to escape in textbox in the bottom, it might be better just to transfer text verbatim because it does not escape for regexp anyway. I see now that the stuff I wanted to write could be written in bottom textbox with double slashes but this was not very intuitive.~~

Edit: Sorry probably misunderstood, I get why encoding to json is needed probably the problem is somewhere else since escaped characters are still not matched for me

**Comment by Predelnik** [comment]
Sorry it looks like everything works in my case after all, so it's probably a misreport
