### ISSUE TITLE
[Feature Request] Unable to change frequency of dynamic updates

### ISSUE THREAD

**Issue by regice202** [pelmers/moz-text-rewriter#13]
Please add this feature to allow for faster dynamic updates!

**Comment by pelmers** [comment]
great idea! I won't be able to get to this for a week, but if anyone's interested in helping it would take the following changes:
1. in prefs.html and prefs.js add a number input field
2. in main.js send the value in 'updateTab'
3. in text-rewriter.js use that value instead of current fixed number

**Comment by pelmers** [comment]
Fixed in https://github.com/pelmers/text-rewriter/commit/e369692a301b784fdff3e47787b684536e0ffb8e, I will submit the new version 1.7.1 this weekend
