### ISSUE TITLE
Import data dupplicate

### ISSUE THREAD

**Issue by hinaftw** [pelmers/moz-text-rewriter#16]
Maybe we need to let dup data overrite the existed one. or add a button to Clear all.

**Comment by pelmers** [comment]
yes, absolutely you're right, it is a bit weird the import is an append instead of overwrite. I originally had the idea that you could use it to put together many different lists.

In case people are used to the existing behavior, I'll add a button to "clear all" of the rules

**Comment by hinaftw** [comment]
Thanks, I'm a Novel editor, so I deal many text file have the name of many fiction characters. I have some suggests as my opinion: 

 - Please set Ignore case as default, I have too many raw name like: kirito, rias...
 - I have two type text to replace: People name and Phrase construct, maybe we have a check box to let theme in something like Label, Subodinate...
 - Sync (optional)

Thank you.

![image](https://user-images.githubusercontent.com/7817474/141416863-206df7a4-6063-4664-a3c0-5d660902bd46.png)

**Comment by pelmers** [comment]
- For changing ignore case together at once, my suggestion is to copy the output code directly and use a text editor to find-replace all the `"ic": false` values to `"ic": false`, then import back
 - I'm not sure what you mean by the theming/labeling, do you have an example of how this should look?
 - I don't plan to implement a sync feature, but you can use dropbox/google drive to share the rewrite lists
