### ISSUE TITLE
Upgrade to WebExtensions

### ISSUE THREAD

**Issue by ghost** [pelmers/moz-text-rewriter#4]
From the [Addons SDK page](https://developer.mozilla.org/en-US/Add-ons/SDK):

>Add-ons using the techniques described in this document are considered a legacy technology in Firefox. Don't use these techniques to develop new add-ons. Use WebExtensions instead. If you maintain an add-on which uses the techniques described here, consider migrating it to use [WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions).

>From Firefox 53 onwards, no new legacy add-ons will be accepted on addons.mozilla.org (AMO).

>From Firefox 57 onwards, WebExtensions will be the only supported extension type, and Firefox will not load other types.

>Even before Firefox 57, changes coming up in the Firefox platform will break many legacy extensions. These changes include multiprocess Firefox (e10s), sandboxing, and multiple content processes. Legacy extensions that are affected by these changes should migrate to WebExtensions if they can. See the "Compatibility Milestones" document for more.

>A wiki page containing resources, migration paths, office hours, and more, is available to help developers transition to the new technologies.

**Comment by pelmers** [comment]
fixed in 0a5f83e039142d42b18f2ab9b9a026cbdc15b2a1
