### ISSUE TITLE
[Feature Request] Ability to limit replacements to some websites

### ISSUE THREAD

**Issue by FatOrangutan** [pelmers/moz-text-rewriter#6]
Currently, all replacements apply to all pages. I have a few replacements (e.g. replacing accented characters with their unaccented counterparts to allow more reliable ctrl+f's) that I would like to limit to a few domains only.

Would be great if you could consider this. Thanks.

**Comment by pelmers** [comment]
Hi, I've started work on this feature!

**Comment by Robert-Riedl** [comment]
Whats the progress on that feature ?

**Comment by pelmers** [comment]
Hi @Robert-Riedl, I did get a prototype of it working a while ago, but wasn't happy with how it bloated the preferences page. But since then haven't revisited it.

**Comment by Robert-Riedl** [comment]
Hi @pelmers that's a pity.
I'm one of those guys who has hundreds of tabs open, so performance tanks because the plugin has so many tabs to parse. 
A way to narrow it down to one domain or one tab or something like that would be a great help.

**Comment by pelmers** [comment]
![Screen Shot 2022-01-03 at 9 39 09 PM](https://user-images.githubusercontent.com/2406051/147978005-dec42c0b-6518-4488-96e0-d403b18e8029.png)

added
